//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public string StoreID { get; set; }
        public string BrandID { get; set; }
        public string SecretKey { get; set; }
        public string Token { get; set; }
        public string DevicePassword { get; set; }
    
        public virtual Brand Brand { get; set; }
    }
}
